name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please 📦
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
          package-name: codecompanion-extra.nvim

      - name: Checkout Repository 🛎️
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Tag Release 🏷️
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "Release ${{ steps.release.outputs.tag_name }} was created!"
          echo "Major: ${{ steps.release.outputs.major }}"
          echo "Minor: ${{ steps.release.outputs.minor }}"
          echo "Patch: ${{ steps.release.outputs.patch }}"
